# Copyright 2025 KU Leuven.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

DEFINES += +define+TSMC_INITIALIZE_MEM

include ../common.mk
