onerror {resume}
quietly virtual function -install /tb_energy_monitor/dut -env /tb_energy_monitor/dut { (concat_ascending)&{/tb_energy_monitor/dut/spin_flipped[63], /tb_energy_monitor/dut/spin_flipped[62], /tb_energy_monitor/dut/spin_flipped[61], /tb_energy_monitor/dut/spin_flipped[60], /tb_energy_monitor/dut/spin_flipped[59], /tb_energy_monitor/dut/spin_flipped[58], /tb_energy_monitor/dut/spin_flipped[57], /tb_energy_monitor/dut/spin_flipped[56], /tb_energy_monitor/dut/spin_flipped[55], /tb_energy_monitor/dut/spin_flipped[54], /tb_energy_monitor/dut/spin_flipped[53], /tb_energy_monitor/dut/spin_flipped[52], /tb_energy_monitor/dut/spin_flipped[51], /tb_energy_monitor/dut/spin_flipped[50], /tb_energy_monitor/dut/spin_flipped[49], /tb_energy_monitor/dut/spin_flipped[48], /tb_energy_monitor/dut/spin_flipped[47], /tb_energy_monitor/dut/spin_flipped[46], /tb_energy_monitor/dut/spin_flipped[45], /tb_energy_monitor/dut/spin_flipped[44], /tb_energy_monitor/dut/spin_flipped[43], /tb_energy_monitor/dut/spin_flipped[42], /tb_energy_monitor/dut/spin_flipped[41], /tb_energy_monitor/dut/spin_flipped[40], /tb_energy_monitor/dut/spin_flipped[39], /tb_energy_monitor/dut/spin_flipped[38], /tb_energy_monitor/dut/spin_flipped[37], /tb_energy_monitor/dut/spin_flipped[36], /tb_energy_monitor/dut/spin_flipped[35], /tb_energy_monitor/dut/spin_flipped[34], /tb_energy_monitor/dut/spin_flipped[33], /tb_energy_monitor/dut/spin_flipped[32], /tb_energy_monitor/dut/spin_flipped[31], /tb_energy_monitor/dut/spin_flipped[30], /tb_energy_monitor/dut/spin_flipped[29], /tb_energy_monitor/dut/spin_flipped[28], /tb_energy_monitor/dut/spin_flipped[27], /tb_energy_monitor/dut/spin_flipped[26], /tb_energy_monitor/dut/spin_flipped[25], /tb_energy_monitor/dut/spin_flipped[24], /tb_energy_monitor/dut/spin_flipped[23], /tb_energy_monitor/dut/spin_flipped[22], /tb_energy_monitor/dut/spin_flipped[21], /tb_energy_monitor/dut/spin_flipped[20], /tb_energy_monitor/dut/spin_flipped[19], /tb_energy_monitor/dut/spin_flipped[18], /tb_energy_monitor/dut/spin_flipped[17], /tb_energy_monitor/dut/spin_flipped[16], /tb_energy_monitor/dut/spin_flipped[15], /tb_energy_monitor/dut/spin_flipped[14], /tb_energy_monitor/dut/spin_flipped[13], /tb_energy_monitor/dut/spin_flipped[12], /tb_energy_monitor/dut/spin_flipped[11], /tb_energy_monitor/dut/spin_flipped[10], /tb_energy_monitor/dut/spin_flipped[9], /tb_energy_monitor/dut/spin_flipped[8], /tb_energy_monitor/dut/spin_flipped[7], /tb_energy_monitor/dut/spin_flipped[6], /tb_energy_monitor/dut/spin_flipped[5], /tb_energy_monitor/dut/spin_flipped[4], /tb_energy_monitor/dut/spin_flipped[3], /tb_energy_monitor/dut/spin_flipped[2], /tb_energy_monitor/dut/spin_flipped[1], /tb_energy_monitor/dut/spin_flipped[0] }} firs64flipped
quietly virtual function -install /tb_energy_monitor/dut -env /tb_energy_monitor/dut { &{/tb_energy_monitor/dut/spin_flipped[0], /tb_energy_monitor/dut/spin_flipped[1], /tb_energy_monitor/dut/spin_flipped[2], /tb_energy_monitor/dut/spin_flipped[3], /tb_energy_monitor/dut/spin_flipped[4], /tb_energy_monitor/dut/spin_flipped[5], /tb_energy_monitor/dut/spin_flipped[6], /tb_energy_monitor/dut/spin_flipped[7], /tb_energy_monitor/dut/spin_flipped[8], /tb_energy_monitor/dut/spin_flipped[9], /tb_energy_monitor/dut/spin_flipped[10], /tb_energy_monitor/dut/spin_flipped[11], /tb_energy_monitor/dut/spin_flipped[12], /tb_energy_monitor/dut/spin_flipped[13], /tb_energy_monitor/dut/spin_flipped[14], /tb_energy_monitor/dut/spin_flipped[15], /tb_energy_monitor/dut/spin_flipped[16], /tb_energy_monitor/dut/spin_flipped[17], /tb_energy_monitor/dut/spin_flipped[18], /tb_energy_monitor/dut/spin_flipped[19], /tb_energy_monitor/dut/spin_flipped[20], /tb_energy_monitor/dut/spin_flipped[21], /tb_energy_monitor/dut/spin_flipped[22], /tb_energy_monitor/dut/spin_flipped[23], /tb_energy_monitor/dut/spin_flipped[24], /tb_energy_monitor/dut/spin_flipped[25], /tb_energy_monitor/dut/spin_flipped[26], /tb_energy_monitor/dut/spin_flipped[27], /tb_energy_monitor/dut/spin_flipped[28], /tb_energy_monitor/dut/spin_flipped[29], /tb_energy_monitor/dut/spin_flipped[30], /tb_energy_monitor/dut/spin_flipped[31], /tb_energy_monitor/dut/spin_flipped[32], /tb_energy_monitor/dut/spin_flipped[33], /tb_energy_monitor/dut/spin_flipped[34], /tb_energy_monitor/dut/spin_flipped[35], /tb_energy_monitor/dut/spin_flipped[36], /tb_energy_monitor/dut/spin_flipped[37], /tb_energy_monitor/dut/spin_flipped[38], /tb_energy_monitor/dut/spin_flipped[39], /tb_energy_monitor/dut/spin_flipped[40], /tb_energy_monitor/dut/spin_flipped[41], /tb_energy_monitor/dut/spin_flipped[42], /tb_energy_monitor/dut/spin_flipped[43], /tb_energy_monitor/dut/spin_flipped[44], /tb_energy_monitor/dut/spin_flipped[45], /tb_energy_monitor/dut/spin_flipped[46], /tb_energy_monitor/dut/spin_flipped[47], /tb_energy_monitor/dut/spin_flipped[48], /tb_energy_monitor/dut/spin_flipped[49], /tb_energy_monitor/dut/spin_flipped[50], /tb_energy_monitor/dut/spin_flipped[51], /tb_energy_monitor/dut/spin_flipped[52], /tb_energy_monitor/dut/spin_flipped[53], /tb_energy_monitor/dut/spin_flipped[54], /tb_energy_monitor/dut/spin_flipped[55], /tb_energy_monitor/dut/spin_flipped[56], /tb_energy_monitor/dut/spin_flipped[57], /tb_energy_monitor/dut/spin_flipped[58], /tb_energy_monitor/dut/spin_flipped[59], /tb_energy_monitor/dut/spin_flipped[60], /tb_energy_monitor/dut/spin_flipped[61], /tb_energy_monitor/dut/spin_flipped[62], /tb_energy_monitor/dut/spin_flipped[63] }} z
quietly WaveActivateNextPane {} 0
add wave -noupdate -radix binary -childformat {{{/tb_energy_monitor/dut/spin_flipped_interleaved_array[3]} -radix binary} {{/tb_energy_monitor/dut/spin_flipped_interleaved_array[2]} -radix binary} {{/tb_energy_monitor/dut/spin_flipped_interleaved_array[1]} -radix binary} {{/tb_energy_monitor/dut/spin_flipped_interleaved_array[0]} -radix binary}} -expand -subitemconfig {{/tb_energy_monitor/dut/spin_flipped_interleaved_array[3]} {-color Yellow -radix binary} {/tb_energy_monitor/dut/spin_flipped_interleaved_array[2]} {-color Yellow -radix binary} {/tb_energy_monitor/dut/spin_flipped_interleaved_array[1]} {-color Yellow -radix binary} {/tb_energy_monitor/dut/spin_flipped_interleaved_array[0]} {-color Yellow -radix binary}} /tb_energy_monitor/dut/spin_flipped_interleaved_array
add wave -noupdate /tb_energy_monitor/dut/spin_handshake
add wave -noupdate -radix unsigned -childformat {{{/tb_energy_monitor/dut/flipped_positions_array[3]} -radix unsigned} {{/tb_energy_monitor/dut/flipped_positions_array[2]} -radix unsigned} {{/tb_energy_monitor/dut/flipped_positions_array[1]} -radix unsigned} {{/tb_energy_monitor/dut/flipped_positions_array[0]} -radix unsigned}} -expand -subitemconfig {{/tb_energy_monitor/dut/flipped_positions_array[3]} {-radix unsigned} {/tb_energy_monitor/dut/flipped_positions_array[2]} {-radix unsigned} {/tb_energy_monitor/dut/flipped_positions_array[1]} {-radix unsigned} {/tb_energy_monitor/dut/flipped_positions_array[0]} {-radix unsigned}} /tb_energy_monitor/dut/flipped_positions_array
add wave -noupdate /tb_energy_monitor/dut/z
add wave -noupdate /tb_energy_monitor/dut/spin_flipped
add wave -noupdate -radix unsigned -childformat {{{/tb_energy_monitor/dut/weight_raddr_em_o[3]} -radix unsigned} {{/tb_energy_monitor/dut/weight_raddr_em_o[2]} -radix unsigned} {{/tb_energy_monitor/dut/weight_raddr_em_o[1]} -radix unsigned} {{/tb_energy_monitor/dut/weight_raddr_em_o[0]} -radix unsigned}} -expand -subitemconfig {{/tb_energy_monitor/dut/weight_raddr_em_o[3]} {-color Magenta -radix unsigned} {/tb_energy_monitor/dut/weight_raddr_em_o[2]} {-color Magenta -radix unsigned} {/tb_energy_monitor/dut/weight_raddr_em_o[1]} {-color Magenta -radix unsigned} {/tb_energy_monitor/dut/weight_raddr_em_o[0]} {-color Magenta -radix unsigned}} /tb_energy_monitor/dut/weight_raddr_em_o
add wave -noupdate /tb_energy_monitor/dut/max_flipped_count_valid
add wave -noupdate /tb_energy_monitor/dut/weight_handshake
add wave -noupdate -radix decimal /tb_energy_monitor/dut/energy_o
add wave -noupdate -radix decimal /tb_energy_monitor/dut/local_energy_parallel
add wave -noupdate -radix unsigned /tb_energy_monitor/dut/counter_q_diff
add wave -noupdate -radix binary /tb_energy_monitor/dut/current_spin
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {183912 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 394
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {180053 ps} {194549 ps}
